// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * Microsoft Playwright Reporting
 * feature to upload report generated by html in customer's storage account and
 * view them in the service portal for faster and easier troubleshooting.
 *
 * @packageDocumentation
 */

import playwrightReporter from "./playwrightReporter.js";

export default playwrightReporter;
