trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: "@azure/service-bus"
      ServiceDirectory: servicebus
      UseFederatedAuth: true
      TimeoutInMinutes: 120
      Clouds: 'Public,Canary'
      SupportedClouds: 'Public'
      CloudConfig:
        Public:
          ServiceConnection: azure-sdk-tests
          SubscriptionConfigurationFilePaths:
            - eng/common/TestResources/sub-config/AzurePublicMsft.json
        UsGov:
          ServiceConnection: usgov_azure-sdk-tests
          SubscriptionConfigurationFilePaths:
            - eng/common/TestResources/sub-config/AzureUsGovMsft.json
          Location: 'usgovarizona'
        China:
          ServiceConnection: china_azure-sdk-tests
          SubscriptionConfigurationFilePaths:
            - eng/common/TestResources/sub-config/AzureChinaMsft.json
          Location: 'chinaeast'
      EnvVars:
        MatrixJobFilter: ubuntu2004_20x_node
